# Generated by Django 4.1.7 on 2024-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milk',
            name='liter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='milk',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
